modLoader="javafml"
loaderVersion="${loader_version_range}"

license="MIT"

[[mods]]

modId="simplest_paxels"

version="1.0.5"

displayName="Simplest Paxels"

authors="Team Solar"

description='''Vanilla paxels: pickaxe + axe + shovel in one.'''

logoFile = "icon.png"


[[dependencies.simplest_paxels]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.simplest_paxels]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"